version: '3.8'
services:
  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=ibmec-trading-bot
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=admin123
    ports:
      - "3301:3306"
    volumes:
      - /c/volumes/mysql_data:/var/lib/mysql
  app:
    build: .
    ports:
      - "80:80" #80 para internet e 8080 para o container
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/ibmec-trading-bot
      - SPRING_DATASOURCE_USERNAME=mysql
      - SPRING_DATASOURCE_PASSWORD=admin123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true